/**
 * ============================================================================
 * NPK Spectrometer Optical Calibration & Edge Inference Engine
 * Multi-Range Tiered Concentration Sensing (Auto-Switching Architecture)
 * Specialized 3-Tier Calibration for Nitrogen & Phosphorus: 0-1, 1-10, 10-100+ mg/L
 * Project: Digital Agriphysics & AI Soil Nutrient Sensing (RBRU)
 * Auto-generated by npk_master_pipeline.py
 * ============================================================================
 */

#ifndef NPK_CALIBRATION_MATRICES_H
#define NPK_CALIBRATION_MATRICES_H

#include <math.h>

// ----------------------------------------------------------------------------
// 1. NITROGEN 3-TIER CALIBRATION COEFFICIENTS
// ----------------------------------------------------------------------------
// Tier 1: Ultra-Low Range (0 - 1.0 mg/L) - Blue Channel High Sensitivity (R2 = 0.9998)
#define NITROGEN_R0_1_SLOPE       (0.065100f)
#define NITROGEN_R0_1_INTERCEPT   (0.000333f)
#define NITROGEN_R0_1_LOD         (0.101f)
#define NITROGEN_R0_1_LOQ         (0.307f)
#define NITROGEN_SWITCH_0_1_ABS   (0.065f) // Transition point at ~1.0 mg/L

// Tier 2: Mid Range (1.0 - 10.0 mg/L) - Blue Channel Agronomic Range (R2 = 0.9933)
#define NITROGEN_R1_10_SLOPE      (0.069972f)
#define NITROGEN_R1_10_INTERCEPT  (-0.019138f)
#define NITROGEN_R1_10_LOD        (0.24f)
#define NITROGEN_R1_10_LOQ        (0.71f)
#define NITROGEN_SWITCH_1_10_ABS  (0.680f) // Threshold on Blue Channel (~10 mg/L)

// Tier 3: High-Range (10 - 100 mg/L) - Green Channel Extended Range (R2 = 0.9366)
#define NITROGEN_HR_SLOPE         (0.012448f)
#define NITROGEN_HR_INTERCEPT     (0.257960f)

// ----------------------------------------------------------------------------
// 2. PHOSPHORUS 3-TIER CALIBRATION COEFFICIENTS
// ----------------------------------------------------------------------------
// Tier 1: Ultra-Low Range (0 - 1.0 mg/L) - Red Channel Ultra-High Precision (R2 = 0.7340)
#define PHOSPHORUS_R0_1_SLOPE     (0.154242f)
#define PHOSPHORUS_R0_1_INTERCEPT (0.024202f)
#define PHOSPHORUS_R0_1_LOD       (0.107f)
#define PHOSPHORUS_R0_1_LOQ       (0.324f)
#define PHOSPHORUS_SWITCH_0_1_ABS (0.230f) // Transition point at ~1.0 mg/L

// Tier 2: Mid Range (1.0 - 10.0 mg/L) - Quadratic Polynomial Inversion (R2 = 0.9925)
#define PHOSPHORUS_R1_10_A         (-0.007270f)
#define PHOSPHORUS_R1_10_B         (0.123704f)
#define PHOSPHORUS_R1_10_C         (-0.006034f)
#define PHOSPHORUS_R1_10_LOD       (0.37f)
#define PHOSPHORUS_R1_10_LOQ       (1.11f)
#define PHOSPHORUS_SWITCH_1_10_ABS (0.510f) // Transition point at ~10.0 mg/L

// Tier 3: High Range (10 - 1000 mg/L) - Red Channel Semi-Log (R2 = 0.9696)
#define PHOSPHORUS_HR_SLOPE        (0.144449f)
#define PHOSPHORUS_HR_INTERCEPT    (0.375476f)

/**
 * Computes Optical Absorbance with Dark Current Subtraction
 * A = -log10( (I_white - I_off) / (I0_white - I0_off) )
 */
static inline float compute_net_absorbance(float sample_white, float sample_off, float blank_white, float blank_off) {
    float net_sample = sample_white - sample_off;
    float net_blank = blank_white - blank_off;
    if (net_blank < 1.0f) net_blank = 1.0f;
    if (net_sample < 0.1f) net_sample = 0.1f;
    
    float ratio = net_sample / net_blank;
    if (ratio > 1.0f) ratio = 1.0f;
    if (ratio < 0.0001f) ratio = 0.0001f;
    
    return -log10f(ratio);
}

/**
 * 3-Tier Auto-Switching Inference for Nitrogen (mg/L)
 * Seamlessly switches between:
 *   - Tier 1: 0 - 1.0 mg/L (Ultra-Low Range, Blue Channel, R2 = 0.9998)
 *   - Tier 2: 1.0 - 10.0 mg/L (Mid Range, Blue Channel, R2 = 0.9933)
 *   - Tier 3: 10 - 100 mg/L (High Range, Green Channel, R2 = 0.9366)
 */
static inline float predict_nitrogen_autorun(float a_blue, float a_green) {
    if (a_blue <= NITROGEN_SWITCH_0_1_ABS) {
        // Tier 1: Ultra-Low Range (0 - 1.0 mg/L)
        float c = (a_blue - NITROGEN_R0_1_INTERCEPT) / NITROGEN_R0_1_SLOPE;
        return (c < 0.0f) ? 0.0f : ((c > 1.0f) ? 1.0f : c);
    } else if (a_blue <= NITROGEN_SWITCH_1_10_ABS) {
        // Tier 2: Mid Range (1.0 - 10.0 mg/L)
        float c = (a_blue - NITROGEN_R1_10_INTERCEPT) / NITROGEN_R1_10_SLOPE;
        return (c < 1.0f) ? 1.0f : ((c > 10.0f) ? 10.0f : c);
    } else {
        // Tier 3: High Range (10 - 100 mg/L Green Channel)
        float c = (a_green - NITROGEN_HR_INTERCEPT) / NITROGEN_HR_SLOPE;
        return (c < 10.0f) ? 10.0f : c;
    }
}

/**
 * 3-Tier Auto-Switching Inference for Phosphorus (mg/L)
 * Seamlessly switches between:
 *   - Tier 1: 0 - 1.0 mg/L (Ultra-High sensitivity, R2 = 0.7340)
 *   - Tier 2: 1.0 - 10.0 mg/L (Quadratic Inversion, R2 = 0.9925)
 *   - Tier 3: 10 - 1000 mg/L (Semi-Log mode for fertilizer solutions)
 */
static inline float predict_phosphorus_autorun(float a_red) {
    if (a_red <= PHOSPHORUS_SWITCH_0_1_ABS) {
        // Tier 1: Ultra-Low Range (0 - 1.0 mg/L Linear)
        float c = (a_red - PHOSPHORUS_R0_1_INTERCEPT) / PHOSPHORUS_R0_1_SLOPE;
        return (c < 0.0f) ? 0.0f : ((c > 1.0f) ? 1.0f : c);
    } else if (a_red <= PHOSPHORUS_SWITCH_1_10_ABS) {
        // Tier 2: Mid Range (1.0 - 10.0 mg/L Quadratic Inversion: C = (-b + sqrt(b^2 - 4a(c - A))) / (2a))
        float disc = (PHOSPHORUS_R1_10_B * PHOSPHORUS_R1_10_B) - 4.0f * PHOSPHORUS_R1_10_A * (PHOSPHORUS_R1_10_C - a_red);
        if (disc < 0.0f) disc = 0.0f;
        float c = (-PHOSPHORUS_R1_10_B + sqrtf(disc)) / (2.0f * PHOSPHORUS_R1_10_A);
        return (c < 1.0f) ? 1.0f : ((c > 10.0f) ? 10.0f : c);
    } else {
        // Tier 3: High Range (10 - 1000 mg/L Semi-Log)
        float log_c = (a_red - PHOSPHORUS_HR_INTERCEPT) / PHOSPHORUS_HR_SLOPE;
        float c = powf(10.0f, log_c);
        return (c < 10.0f) ? 10.0f : c;
    }
}

/**
 * Turbidity-corrected Multi-channel Evaluation
 */
static inline void evaluate_soil_nutrients_tiered(float a_red, float a_green, float a_blue, float a_clear,
                                                 float* out_n_mg_l, float* out_p_mg_l) {
    // Clear channel baseline scattering compensation (alpha = 0.15)
    float a_blue_corr  = a_blue  - (a_clear * 0.15f);
    float a_green_corr = a_green - (a_clear * 0.15f);
    float a_red_corr   = a_red   - (a_clear * 0.15f);
    
    if (a_blue_corr < 0.0f) a_blue_corr = 0.0f;
    if (a_green_corr < 0.0f) a_green_corr = 0.0f;
    if (a_red_corr < 0.0f) a_red_corr = 0.0f;
    
    *out_n_mg_l = predict_nitrogen_autorun(a_blue_corr, a_green_corr);
    *out_p_mg_l = predict_phosphorus_autorun(a_red_corr);
}

#endif // NPK_CALIBRATION_MATRICES_H
