/**
 * TinyML_Model.h
 * Deep Neural Network Calibration Model for Wio Terminal Soil Spectrometer
 * Architecture: 6 -> 12 -> 8 -> 3 (Multi-task NPK Estimation with Turbidity Compensation)
 * Generated by AI4D AgriPhysics - Rambhai Barni Rajabhat University (RBRU)
 * Test Performance: N_R2=0.992, P_R2=0.988, K_R2=0.990
 */

#ifndef TINYML_MODEL_H
#define TINYML_MODEL_H

#include <Arduino.h>

#define TINYML_INPUT_DIM   6
#define TINYML_HIDDEN1_DIM 12
#define TINYML_HIDDEN2_DIM 8
#define TINYML_OUTPUT_DIM  3

// Feature Scaler Parameters (Z-Score Standardization)
const float TINYML_FEATURE_MEANS[6] = {33.240311f, 30.758058f, 36.001631f, 1.218440f, 1.993948f, 0.388170f};
const float TINYML_FEATURE_SCALES[6] = {7.321222f, 6.145682f, 6.406134f, 0.076351f, 0.461110f, 0.224489f};

// Layer 1 Weights: (6, 12)
const float TINYML_W1[6][12] = {
  {-0.660492f, 1.045962f, 1.140588f, -0.353854f, -0.111623f, -0.644638f, -1.643084f, 0.066591f, 1.090599f, 0.281907f, -0.466852f, 0.321666f},
  {0.977239f, -0.339747f, -1.426323f, -0.087118f, -0.837416f, 0.387848f, -1.395585f, 0.090595f, 0.492162f, -0.284723f, -0.417515f, 0.052675f},
  {0.466177f, 0.102539f, -0.993789f, 0.205404f, 0.136961f, -1.089233f, 1.691663f, -0.159479f, -1.435794f, 0.763450f, 0.252694f, 0.271633f},
  {-0.013270f, -0.429568f, 0.397462f, 0.111598f, -0.225953f, 0.069810f, 0.114652f, 0.040198f, -0.016466f, 0.618163f, -0.030243f, -0.006047f},
  {-0.128769f, -0.616538f, 0.587993f, -0.164149f, 0.628670f, 0.325778f, 0.033218f, -0.036019f, -0.315339f, -0.229520f, -0.043665f, -0.009868f},
  {1.713271f, 0.999965f, 1.680439f, 1.817850f, 1.011900f, 1.148498f, 2.247324f, 2.855980f, 1.498688f, 1.525709f, 1.399758f, -0.123451f},
};

const float TINYML_B1[12] = {1.572834f, 2.545802f, 2.082914f, 3.322745f, 2.515525f, 2.315593f, 1.319755f, -0.731626f, 1.972515f, 2.320383f, 2.337522f, -0.698481f};

// Layer 2 Weights: (12, 8)
const float TINYML_W2[12][8] = {
  {-0.000000f, 0.024327f, 1.161024f, 0.642095f, -0.593819f, -0.127236f, 2.984331f, 1.959584f},
  {0.200332f, 1.237708f, 1.575442f, 1.111903f, 2.289046f, 0.881333f, -0.420078f, 0.277013f},
  {-0.591323f, 1.083899f, 0.264195f, 0.870878f, 3.427310f, 0.987873f, 1.207456f, 0.282684f},
  {-0.372955f, 1.792845f, 3.015907f, 1.870054f, -0.624157f, 2.538287f, 0.437341f, 3.563138f},
  {0.254143f, 0.642692f, 2.300317f, 1.064982f, 1.679794f, 0.866335f, -1.426580f, 1.371041f},
  {-0.000000f, 1.212591f, 0.745128f, 1.709457f, -1.102206f, 2.498185f, 2.534170f, 0.321973f},
  {-0.444322f, -0.491895f, 2.401057f, -0.300579f, 0.985421f, -1.508521f, 0.281758f, 2.869910f},
  {0.445545f, -1.887064f, -2.695905f, -1.430369f, 0.441056f, -3.510184f, 1.539463f, -2.719762f},
  {-0.542258f, 0.829158f, -0.068515f, 0.586474f, 1.948877f, 2.567617f, 1.831248f, -1.201176f},
  {0.098141f, 1.317385f, 1.158416f, 1.263132f, 2.347084f, 0.179947f, -0.543541f, 1.288661f},
  {-0.522426f, 1.563437f, 1.803075f, 0.916747f, 0.161552f, -0.090076f, -1.102973f, 1.540069f},
  {-0.051021f, -0.064238f, 0.305037f, -0.150932f, 0.089868f, -0.233268f, 0.365971f, -0.484565f},
};

const float TINYML_B2[8] = {-0.273796f, 0.780755f, 1.702849f, 1.521609f, 0.857974f, 1.875385f, 0.218298f, 1.222270f};

// Layer 3 Output Weights: (8, 3)
const float TINYML_W3[8][3] = {
  {0.124688f, -0.293384f, -0.510546f},
  {1.592551f, 1.473275f, 1.617679f},
  {-0.114168f, 0.437987f, 2.155907f},
  {1.376425f, 1.756673f, 1.764085f},
  {2.165534f, -3.668211f, -1.205503f},
  {2.628012f, 2.557232f, -0.537503f},
  {-2.153562f, 2.179012f, -3.148084f},
  {-1.030765f, 0.603825f, 2.531000f},
};

const float TINYML_B3[3] = {0.989281f, 0.562280f, 1.160925f};

// TinyML Forward Pass Inference Engine (Ultra-Fast Zero-Allocation)
inline void tinyml_predict(const float raw_inputs[6], float outputs[3]) {
    // 1. Z-Score Normalization
    float z[TINYML_INPUT_DIM];
    for (int i = 0; i < TINYML_INPUT_DIM; i++) {
        z[i] = (raw_inputs[i] - TINYML_FEATURE_MEANS[i]) / TINYML_FEATURE_SCALES[i];
    }

    // 2. Hidden Layer 1 (6 -> 12 with ReLU)
    float h1[TINYML_HIDDEN1_DIM];
    for (int j = 0; j < TINYML_HIDDEN1_DIM; j++) {
        float sum = TINYML_B1[j];
        for (int i = 0; i < TINYML_INPUT_DIM; i++) {
            sum += z[i] * TINYML_W1[i][j];
        }
        h1[j] = (sum > 0.0f) ? sum : 0.0f; // ReLU
    }

    // 3. Hidden Layer 2 (12 -> 8 with ReLU)
    float h2[TINYML_HIDDEN2_DIM];
    for (int k = 0; k < TINYML_HIDDEN2_DIM; k++) {
        float sum = TINYML_B2[k];
        for (int j = 0; j < TINYML_HIDDEN1_DIM; j++) {
            sum += h1[j] * TINYML_W2[j][k];
        }
        h2[k] = (sum > 0.0f) ? sum : 0.0f; // ReLU
    }

    // 4. Output Layer (8 -> 3 with Linear activation + Clamp)
    for (int m = 0; m < TINYML_OUTPUT_DIM; m++) {
        float sum = TINYML_B3[m];
        for (int k = 0; k < TINYML_HIDDEN2_DIM; k++) {
            sum += h2[k] * TINYML_W3[k][m];
        }
        if (sum < 0.0f) sum = 0.0f;
        if (sum > 500.0f) sum = 500.0f;
        outputs[m] = sum;
    }
}

#endif // TINYML_MODEL_H
