#!/usr/bin/env python3
"""
TinyML Model Trainer and C-Header Generator for Soil NPK Spectrometer
Author: Asst. Prof. Dr. Chewa Thassana & AI4D AgriPhysics Research Unit
Institution: Rambhai Barni Rajabhat University (RBRU)
"""

import numpy as np
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error

def generate_spectroscopy_dataset(num_samples=1200, random_seed=42):
    np.random.seed(random_seed)
    
    # True soil NPK values (mg/kg)
    N_true = np.random.uniform(5.0, 250.0, num_samples)
    P_true = np.random.uniform(5.0, 200.0, num_samples)
    K_true = np.random.uniform(5.0, 300.0, num_samples)
    
    # Turbidity and Humus color interference (Matrix effect)
    turbidity = np.random.uniform(0.05, 0.35, num_samples)
    humus_color = np.random.uniform(0.02, 0.20, num_samples)
    
    # Optical response functions with physical cross-talk
    # Nitrogen mainly alters Blue absorption, but has minor Green cross-talk
    b_resp = 28.0 + 0.38 * N_true - 0.00045 * (N_true**2) + 12.0 * turbidity + np.random.normal(0, 0.8, num_samples)
    # Phosphorus mainly alters Green absorption, with minor Blue/Red cross-talk
    g_resp = 32.0 + 0.32 * P_true - 0.00038 * (P_true**2) + 14.0 * turbidity + 8.0 * humus_color + np.random.normal(0, 0.7, num_samples)
    # Potassium causes precipitation scattering (altering Red)
    r_resp = 40.0 + 0.26 * K_true - 0.00025 * (K_true**2) + 15.0 * turbidity + np.random.normal(0, 0.9, num_samples)
    
    # Normalize RGB percentages
    total_rgb = b_resp + g_resp + r_resp
    bp = (b_resp / total_rgb) * 100.0
    gp = (g_resp / total_rgb) * 100.0
    rp = (r_resp / total_rgb) * 100.0
    
    # Clear channel ratio (proxy for total transmission / turbidity)
    c_ratio = 1.05 + 0.85 * turbidity + np.random.normal(0, 0.02, num_samples)
    lux_norm = np.random.uniform(1.2, 2.8, num_samples)
    abs_est = -np.log10(np.clip(1.0 - (0.0015 * N_true + 0.0018 * P_true + 0.0012 * K_true) + 0.05 * turbidity, 0.05, 0.98))
    
    # Feature matrix X: [bp, gp, rp, c_ratio, lux_norm, abs_est]
    X = np.column_stack([bp, gp, rp, c_ratio, lux_norm, abs_est])
    # Target matrix Y: [N, P, K]
    Y = np.column_stack([N_true, P_true, K_true])
    
    return X, Y

def train_and_export_header(output_header_path="TinyML_Model.h"):
    print("[1/4] Generating spectroscopic calibration dataset...")
    X, Y = generate_spectroscopy_dataset(num_samples=1500)
    
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
    
    # Standardize features
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    
    print("[2/4] Training Edge AI Multi-Layer Perceptron (Architecture: 6 -> 12 -> 8 -> 3)...")
    mlp = MLPRegressor(
        hidden_layer_sizes=(12, 8),
        activation='relu',
        solver='adam',
        max_iter=1000,
        learning_rate_init=0.008,
        random_state=42,
        early_stopping=True,
        n_iter_no_change=25
    )
    mlp.fit(X_train_scaled, Y_train)
    
    # Evaluation
    Y_pred = mlp.predict(X_test_scaled)
    r2_scores = [r2_score(Y_test[:, i], Y_pred[:, i]) for i in range(3)]
    rmse_scores = [np.sqrt(mean_squared_error(Y_test[:, i], Y_pred[:, i])) for i in range(3)]
    
    print(f"       Model Evaluation Results:")
    print(f"       - Nitrogen (N):   R2 = {r2_scores[0]:.4f}, RMSE = {rmse_scores[0]:.2f} mg/kg")
    print(f"       - Phosphorus (P): R2 = {r2_scores[1]:.4f}, RMSE = {rmse_scores[1]:.2f} mg/kg")
    print(f"       - Potassium (K):  R2 = {r2_scores[2]:.4f}, RMSE = {rmse_scores[2]:.2f} mg/kg")
    
    print(f"[3/4] Exporting optimized C++ TinyML header to {output_header_path}...")
    
    # Extract weights & biases
    W0 = mlp.coefs_[0]  # (6, 12)
    b0 = mlp.intercepts_[0]  # (12,)
    W1 = mlp.coefs_[1]  # (12, 8)
    b1 = mlp.intercepts_[1]  # (8,)
    W2 = mlp.coefs_[2]  # (8, 3)
    b2 = mlp.intercepts_[2]  # (3,)
    
    means = scaler.mean_
    scales = scaler.scale_
    
    with open(output_header_path, "w", encoding="utf-8") as f:
        f.write("/**\n")
        f.write(" * TinyML_Model.h\n")
        f.write(" * Deep Neural Network Calibration Model for Wio Terminal Soil Spectrometer\n")
        f.write(" * Architecture: 6 -> 12 -> 8 -> 3 (Multi-task NPK Estimation with Turbidity Compensation)\n")
        f.write(" * Generated by AI4D AgriPhysics - Rambhai Barni Rajabhat University (RBRU)\n")
        f.write(f" * Test Performance: N_R2={r2_scores[0]:.3f}, P_R2={r2_scores[1]:.3f}, K_R2={r2_scores[2]:.3f}\n")
        f.write(" */\n\n")
        f.write("#ifndef TINYML_MODEL_H\n")
        f.write("#define TINYML_MODEL_H\n\n")
        f.write("#include <Arduino.h>\n\n")
        
        f.write("#define TINYML_INPUT_DIM   6\n")
        f.write("#define TINYML_HIDDEN1_DIM 12\n")
        f.write("#define TINYML_HIDDEN2_DIM 8\n")
        f.write("#define TINYML_OUTPUT_DIM  3\n\n")
        
        # Scaler
        f.write("// Feature Scaler Parameters (Z-Score Standardization)\n")
        f.write(f"const float TINYML_FEATURE_MEANS[6] = {{{', '.join([f'{m:.6f}f' for m in means])}}};\n")
        f.write(f"const float TINYML_FEATURE_SCALES[6] = {{{', '.join([f'{s:.6f}f' for s in scales])}}};\n\n")
        
        # Layer 1
        f.write("// Layer 1 Weights: (6, 12)\n")
        f.write("const float TINYML_W1[6][12] = {\n")
        for row in W0:
            f.write(f"  {{{', '.join([f'{val:.6f}f' for val in row])}}},\n")
        f.write("};\n\n")
        f.write(f"const float TINYML_B1[12] = {{{', '.join([f'{val:.6f}f' for val in b0])}}};\n\n")
        
        # Layer 2
        f.write("// Layer 2 Weights: (12, 8)\n")
        f.write("const float TINYML_W2[12][8] = {\n")
        for row in W1:
            f.write(f"  {{{', '.join([f'{val:.6f}f' for val in row])}}},\n")
        f.write("};\n\n")
        f.write(f"const float TINYML_B2[8] = {{{', '.join([f'{val:.6f}f' for val in b1])}}};\n\n")
        
        # Layer 3
        f.write("// Layer 3 Output Weights: (8, 3)\n")
        f.write("const float TINYML_W3[8][3] = {\n")
        for row in W2:
            f.write(f"  {{{', '.join([f'{val:.6f}f' for val in row])}}},\n")
        f.write("};\n\n")
        f.write(f"const float TINYML_B3[3] = {{{', '.join([f'{val:.6f}f' for val in b2])}}};\n\n")
        
        # Inference function inlined for maximum efficiency
        f.write("""// TinyML Forward Pass Inference Engine (Ultra-Fast Zero-Allocation)
inline void tinyml_predict(const float raw_inputs[6], float outputs[3]) {
    // 1. Z-Score Normalization
    float z[TINYML_INPUT_DIM];
    for (int i = 0; i < TINYML_INPUT_DIM; i++) {
        z[i] = (raw_inputs[i] - TINYML_FEATURE_MEANS[i]) / TINYML_FEATURE_SCALES[i];
    }

    // 2. Hidden Layer 1 (6 -> 12 with ReLU)
    float h1[TINYML_HIDDEN1_DIM];
    for (int j = 0; j < TINYML_HIDDEN1_DIM; j++) {
        float sum = TINYML_B1[j];
        for (int i = 0; i < TINYML_INPUT_DIM; i++) {
            sum += z[i] * TINYML_W1[i][j];
        }
        h1[j] = (sum > 0.0f) ? sum : 0.0f; // ReLU
    }

    // 3. Hidden Layer 2 (12 -> 8 with ReLU)
    float h2[TINYML_HIDDEN2_DIM];
    for (int k = 0; k < TINYML_HIDDEN2_DIM; k++) {
        float sum = TINYML_B2[k];
        for (int j = 0; j < TINYML_HIDDEN1_DIM; j++) {
            sum += h1[j] * TINYML_W2[j][k];
        }
        h2[k] = (sum > 0.0f) ? sum : 0.0f; // ReLU
    }

    // 4. Output Layer (8 -> 3 with Linear activation + Clamp)
    for (int m = 0; m < TINYML_OUTPUT_DIM; m++) {
        float sum = TINYML_B3[m];
        for (int k = 0; k < TINYML_HIDDEN2_DIM; k++) {
            sum += h2[k] * TINYML_W3[k][m];
        }
        if (sum < 0.0f) sum = 0.0f;
        if (sum > 500.0f) sum = 500.0f;
        outputs[m] = sum;
    }
}

#endif // TINYML_MODEL_H
""")
    print("[4/4] TinyML header generated successfully!")

if __name__ == "__main__":
    train_and_export_header("/Users/chewathassana/Downloads/spectrometer_npk2026/firmware/TinyML_Model.h")
